#! /usr/bin/env python3
import sys, re, os

os.system('tsc ' + ' '.join(sys.argv[1:]))

for tsfile in sys.argv[1:]:
    jsfile = tsfile.replace('.ts', '.js')

    with open(jsfile) as file:
        text = file.read()

    for match in re.finditer(r'/// QML (.+)', text):
    	text = match.group(1) + '\n' + text

    text = re.sub(r'/// QML (.+)\n', '', text)
    text = re.sub(r'var \w+ = require(.+);\n', '', text)
    text = re.sub(r'exports.\w+ = \w+;\n', '', text)

    with open(jsfile, 'w') as file:
        file.write(text)
